### ISSUE TITLE
Don't add a "container" within the Component

### ISSUE THREAD

**Issue by gesinn-it-gea** [gesinn-it-pub/ConfIDentSkin#4]
`MainContentWithSideBar.php` adds a `div` `container` that prevents switching modes. See also https://github.com/ProfessionalWiki/chameleon/commit/cf67b8aa87fd22ea634396810ba4d56c93dc0629. A `container` is already set by the grid system.

Lines https://github.com/gesinn-it-pub/ConfIDentSkin/blob/7617da6e794d166a476fd08b49c3a29f77ce64d9/src/Components/MainContentWithSideBar.php#L19 and https://github.com/gesinn-it-pub/ConfIDentSkin/blob/7617da6e794d166a476fd08b49c3a29f77ce64d9/src/Components/MainContentWithSideBar.php#L26 needs to be removed.

**Rationale**:
I'd like to change https://github.com/gesinn-it-pub/ConfIDentSkin/blob/178798dd65fe2f45ae8895a1b3453ac260f639f4/layouts/standard.xml#L14 to `<grid mode="fluid">`

**Comment by gesinn-it-wam** [comment]
Fixed by https://github.com/gesinn-it-pub/ConfIDentSkin/commit/74d54fd5aefd75dc7c52a0e02f020d16aed316e7
